version: '3'
services:
  bms_hv:
    build: 
      context: .
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ./config_hv.yaml:/workdir/config.yaml
      - /dev/bms_hv:/dev/bms_hv
  bms_lv:
    build: 
      context: .
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ./config_lv.yaml:/workdir/config.yaml
      - /dev/bms_lv:/dev/bms_lv
