version: '3'
services:
  bmspace:
    build: 
      context: .
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ./config.yaml:/workdir/config.yaml
      - /dev/ttyUSB1:/dev/ttyUSB1
